// src/components/dashboard/analytics/AiSummaryCard.jsx
//
// An admin-triggered AI narrative of the period. Only aggregate metrics reach
// the model (the server enforces the PII firewall); this card just renders the
// result. Inert-friendly: when the provider isn't configured it shows a calm
// note instead of an error.
import PropTypes from "prop-types";
import { format } from "date-fns";
import { Sparkles, Loader2, AlertTriangle } from "lucide-react";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { useGenerateAiSummary } from "@/hooks/useAdminAnalytics";
import { extractApiErrorMessage } from "@/utils/extract-api-error-message";

// Splits the model's plain text into a headline and bullet/paragraph lines.
function parseSummary(text) {
  const lines = text.split("\n").map((line) => line.trim()).filter(Boolean);
  const headline = lines.find((line) => !line.startsWith("- ") && !line.startsWith("•")) ?? "";
  const items = lines
    .filter((line) => line !== headline)
    .map((line) => line.replace(/^[-•]\s*/, ""));
  return { headline, items };
}

const AiSummaryCard = ({ dateRange }) => {
  const { mutate, data, isPending, isError, error, reset } = useGenerateAiSummary();
  const result = data?.data;

  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between gap-3 space-y-0 pb-3">
        <div>
          <p className="font-mono text-[10px] font-bold uppercase tracking-tight text-muted-foreground">
            Insight
          </p>
          <h3 className="mt-0.5 flex items-center gap-2 font-display text-base font-medium text-foreground sm:text-lg">
            <Sparkles className="h-4 w-4 text-primary" /> AI summary
          </h3>
        </div>
        <Button
          size="sm"
          className="gap-2"
          disabled={isPending}
          onClick={() => {
            reset();
            mutate(dateRange);
          }}
        >
          {isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}
          {result ? "Regenerate" : "Generate"}
        </Button>
      </CardHeader>
      <CardContent>
        {isError ? (
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <AlertTriangle className="h-4 w-4 text-destructive/70" />
            {extractApiErrorMessage(error).message}
          </div>
        ) : isPending ? (
          <p className="text-sm text-muted-foreground">Summarizing this period&apos;s metrics...</p>
        ) : !result ? (
          <p className="text-sm text-muted-foreground">
            Generate a plain-language summary of attendance and integrity for the selected period.
            Only aggregate metrics are used - never individual attendee data.
          </p>
        ) : result.configured === false ? (
          <p className="text-sm text-muted-foreground">
            AI summaries aren&apos;t enabled. Set <code className="rounded bg-muted px-1 py-0.5 text-xs">GEMINI_API_KEY</code> on the server to turn this on.
          </p>
        ) : (
          <div className="space-y-3">
            {(() => {
              const { headline, items } = parseSummary(result.summary || "");
              return (
                <>
                  {headline && <p className="font-medium text-foreground">{headline}</p>}
                  {items.length > 0 && (
                    <ul className="space-y-1.5 text-sm text-muted-foreground">
                      {items.map((item, index) => (
                        <li key={index} className="flex gap-2">
                          <span className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-primary" />
                          <span>{item}</span>
                        </li>
                      ))}
                    </ul>
                  )}
                </>
              );
            })()}
            <p className="border-t border-border pt-3 text-xs text-muted-foreground">
              Generated by {result.model}
              {result.generatedAt ? ` · ${format(new Date(result.generatedAt), "MMM d, HH:mm")}` : ""} · Review before sharing
            </p>
          </div>
        )}
      </CardContent>
    </Card>
  );
};

AiSummaryCard.propTypes = { dateRange: PropTypes.object };

export default AiSummaryCard;
