// scripts/generate-seo.mjs
//
// Generates public/robots.txt and public/sitemap.xml so they never drift by
// hand. Wired as the `prebuild` npm script, so `npm run build` regenerates
// them; also runnable directly with `node scripts/generate-seo.mjs`.
//
// This is plain Node (no Vite), so it cannot import src/lib/site.js (that
// module reads import.meta.env). siteUrl is duplicated minimally here and
// reads the same VITE_SITE_URL env var with the same production fallback.
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const publicDir = resolve(here, "../public");

const rawSiteUrl = process.env.VITE_SITE_URL || "https://bethere.manuru.dev";
const siteUrl = rawSiteUrl.replace(/\/+$/, "");

// Public, indexable routes. The dashboard and auth pages are private.
const publicRoutes = [
  { path: "/", changefreq: "monthly", priority: "1.0" },
  { path: "/privacy-policy", changefreq: "yearly", priority: "0.3" },
  { path: "/terms-of-service", changefreq: "yearly", priority: "0.3" },
];

// Private areas kept out of search results.
const disallow = ["/dashboard", "/login", "/forgot-password", "/reset-password"];

const robots = `# Generated by scripts/generate-seo.mjs - do not edit by hand.
User-agent: *
Allow: /
${disallow.map((path) => `Disallow: ${path}`).join("\n")}

Sitemap: ${siteUrl}/sitemap.xml
`;

const lastmod = new Date().toISOString().slice(0, 10);

const urlEntries = publicRoutes
  .map(
    ({ path, changefreq, priority }) =>
      `  <url>\n    <loc>${siteUrl}${path}</loc>\n    <lastmod>${lastmod}</lastmod>\n    <changefreq>${changefreq}</changefreq>\n    <priority>${priority}</priority>\n  </url>`
  )
  .join("\n");

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-seo.mjs - do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urlEntries}
</urlset>
`;

mkdirSync(publicDir, { recursive: true });
writeFileSync(resolve(publicDir, "robots.txt"), robots);
writeFileSync(resolve(publicDir, "sitemap.xml"), sitemap);

console.log(`Generated public/robots.txt and public/sitemap.xml (siteUrl: ${siteUrl})`);
